version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18  
  pre_build:
    commands:
      - echo "Prebuild"
      - sleep 10  
  build:
    commands:
      - echo "Build"
      - sleep 10
      - exit 1
  post_build:
    commands:
      - echo "Postbuild"
      - sleep 10
      - echo "test" > test.json
artifacts:
  files:
    - test.json
